select A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * (1-C.DISCOUNT_RATE/100)) AS FEE from CAR_RENTAL_COMPANY_CAR A
join CAR_RENTAL_COMPANY_RENTAL_HISTORY B on A.CAR_ID = B.CAR_ID
join CAR_RENTAL_COMPANY_DISCOUNT_PLAN C on A.CAR_TYPE = C.CAR_TYPE
where A.CAR_TYPE in ('세단', 'SUV')
and not A.CAR_ID in (
        SELECT h.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h       
        WHERE h.END_DATE >= 20221101)
and A.DAILY_FEE * 30 * (1-C.DISCOUNT_RATE/100) >= 500000 and A.DAILY_FEE * 30 * (1-C.DISCOUNT_RATE/100) < 2000000
and C.DURATION_TYPE = '30일 이상'
group by A.CAR_ID
order by FEE DESC, A.CAR_TYPE DESC, A.CAR_ID DESC