select YEAR(sales_date) AS YEAR,
    MONTH(sales_date) AS MONTH, 
    count(DISTINCT A.USER_ID) AS PURCHASED_USERS, 
    ROUND(count(DISTINCT A.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATIO
from ONLINE_SALE A
inner join USER_INFO B on A.USER_ID = B.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH