select A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT A
join FOOD_ORDER B on A.PRODUCT_ID = B.PRODUCT_ID
where B.PRODUCE_DATE like concat ('2022-05-%')
group by A.PRODUCT_ID
order by TOTAL_SALES DESC, PRODUCT_ID ASC